-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_site character varying(50) NOT NULL,
    phone_number character varying(13) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "position" character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    national_idendity character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personnels
(
    id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employer_verification_by_system_personnels
(
    id integer NOT NULL,
    system_personnel_id integer NOT NULL,
    employer_id integer NOT NULL,
    is_verified boolean NOT NULL,
    verification_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisements
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    job_position_id integer NOT NULL,
    description text NOT NULL,
    city_id integer NOT NULL,
    min_salary double precision NOT NULL,
    max_salary double precision NOT NULL,
    quota integer NOT NULL,
    application_deadline timestamp with time zone NOT NULL,
    "release date" timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_codes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    activation_code character varying(50) NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_personnels
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employer_verification_by_system_personnels
    ADD FOREIGN KEY (system_personnel_id)
    REFERENCES public.system_personnels (id)
    NOT VALID;


ALTER TABLE public.employer_verification_by_system_personnels
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.verification_codes
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;
	
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (1, 'ADANA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (2, 'ADIYAMAN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (3, 'AFYONKARAHİSAR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (4, 'AĞRI');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (5, 'AMASYA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (6, 'ANKARA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (7, 'ANTALYA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (8, 'ARTVİN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (9, 'AYDIN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (10, 'BALIKESİR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (11, 'BİLECİK');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (12, 'BİNGÖL');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (13, 'BİTLİS');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (14, 'BOLU');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (15, 'BURDUR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (16, 'BURSA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (17, 'ÇANAKKALE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (18, 'ÇANKIRI');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (19, 'ÇORUM');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (20, 'DENİZLİ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (21, 'DİYARBAKIR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (22, 'EDİRNE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (23, 'ELAZIĞ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (24, 'ERZİNCAN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (25, 'ERZURUM');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (26, 'ESKİŞEHİR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (27, 'GAZİANTEP');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (28, 'GİRESUN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (29, 'GÜMÜŞHANE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (30, 'HAKKARİ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (31, 'HATAY');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (32, 'ISPARTA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (33, 'MERSİN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (34, 'İSTANBUL');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (35, 'İZMİR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (36, 'KARS');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (37, 'KASTAMONU');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (38, 'KAYSERİ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (39, 'KIRKLARELİ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (40, 'KIRŞEHİR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (41, 'KOCAELİ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (42, 'KONYA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (43, 'KÜTAHYA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (44, 'MALATYA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (45, 'MANİSA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (46, 'KAHRAMANMARAŞ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (47, 'MARDİN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (48, 'MUĞLA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (49, 'MUŞ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (50, 'NEVŞEHİR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (51, 'NİĞDE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (52, 'ORDU');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (53, 'RİZE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (54, 'SAKARYA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (55, 'SAMSUN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (56, 'SİİRT');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (57, 'SİNOP');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (58, 'SİVAS');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (59, 'TEKİRDAĞ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (60, 'TOKAT');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (61, 'TRABZON');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (62, 'TUNCELİ');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (63, 'ŞANLIURFA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (64, 'UŞAK');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (65, 'VAN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (66, 'YOZGAT');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (67, 'ZONGULDAK');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (68, 'AKSARAY');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (69, 'BAYBURT');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (70, 'KARAMAN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (71, 'KIRIKKALE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (72, 'BATMAN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (73, 'ŞIRNAK');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (74, 'BARTIN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (75, 'ARDAHAN');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (76, 'IĞDIR');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (77, 'YALOVA');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (78, 'KARABÜK');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (79, 'KİLİS');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (80, 'OSMANİYE');
INSERT INTO public.cities (id, city_name) OVERRIDING SYSTEM VALUE VALUES (81, 'DÜZCE');


END;
